version: "3.8"
services:
  water-heater:
    build:
      dockerfile: docker/Dockerfile # specify the Dockerfile location
      context: . # specify the build context

    environment:
      POSTGRES_USER: waterHeater # set the Postgres username
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Missing environment variable see readme} # set the Postgres password
      POSTGRES_DB: waterHeater # set the Postgres database name
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN?Missing environment variable see readme} # set the Discord bot token

    restart: always # always restart the container

    depends_on:
      - postgres # depend on the Postgres service

  postgres:
    image: postgres:14.13-alpine # use the Postgres image

    environment:
      POSTGRES_USER: waterHeater # set the Postgres username
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Missing environment variable see readme} # set the Postgres password
      POSTGRES_DB: waterHeater # set the Postgres database name

    volumes:
      - waterHeaterPostgresqlData:/var/lib/postgresql/data # mount the Postgres data volume

    restart: always # always restart the container

volumes:
  waterHeaterPostgresqlData:
    driver: local # use the local driver for the volume