version: "3.8"
services:
  water-heater:
    container_name: waterHeater # set the container name for the water-heater service

  postgres:
    container_name: waterHeaterPostgres # set the container name for the postgres service